---
- hosts: webservers
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Add PHP PPA repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Install PHP 8.3 and required extensions
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php8.3
        - php8.3-fpm
        - php8.3-mysql
        - php8.3-cli
        - php8.3-common
        - php8.3-xml
        - php8.3-mbstring
        - php8.3-curl
        - php8.3-zip

    - name: Start and enable PHP-FPM service
      systemd:
        name: php8.3-fpm
        state: started
        enabled: yes

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL service is running and enabled
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Get PostgreSQL version
      shell: "psql -V | awk '{print $3}' | cut -d '.' -f1,2"
      register: postgresql_version

    - name: Set PostgreSQL admin user password
      shell: sudo -u postgres psql -c "ALTER USER postgres PASSWORD '{{ postgres_password }}';"
      vars:
        postgres_password: "{{ postgres_password }}"

    - name: Allow remote connections to PostgreSQL
      lineinfile:
        path: "/etc/postgresql/{{ postgresql_version.stdout }}/main/postgresql.conf"
        regexp: '^#?(listen_addresses\s*=\s*)\S+'
        line: "listen_addresses = '*'"

    - name: Configure PostgreSQL to accept all IP addresses
      lineinfile:
        path: "/etc/postgresql/{{ postgresql_version.stdout }}/main/pg_hba.conf"
        insertafter: "IPv4 local connections:"
        line: "host    all             all             0.0.0.0/0            md5"

    - name: Restart PostgreSQL to apply changes
      systemd:
        name: postgresql
        state: restarted
